d3d_object_create();
gravity_enabled = true;
vitality = 100;
vision = 500;
_speed = 2;
collision_box_size = 32;
height = 5;
damage = 4;
d = direction;
z = 10;
zspeed = 9;
image_xscale = collision_box_size / sprite_width;
image_yscale = collision_box_size / sprite_height;